#!/usr/bin/env bash
#
# impact-scan.sh — one-shot symbol triage before editing (search-first-context rule 2).
#
# Usage: impact-scan.sh <identifier> [dir]
#
# Greps <identifier> (fixed-string match) repo-wide under [dir] (default: .), skipping
# common ignore dirs (.git, node_modules, dist, build, vendor, __pycache__), and buckets
# every file containing hits by path heuristics:
#
#   caller    — source that references the identifier. This bucket gates your edit and
#               STILL REQUIRES MANUAL READS: open every caller that could pass a
#               different shape BEFORE the first edit (rule 2d). The script replaces
#               only the grep + classification steps, never the reads.
#   test      — test/spec/fixture files. They may pin the current behavior; update them
#               deliberately, never reflexively (verifying-before-claiming rule 10).
#   generated — build outputs, snapshots, lockfiles, or files whose header says
#               AUTO-GENERATED / DO NOT EDIT / @generated. Never the edit target;
#               fix the source or the generator instead (rule 4).
#   vendored  — third-party copies (third_party/, .venv/, site-packages/, ...).
#               Never edit; the change belongs upstream or in a wrapper.
#   docs      — markdown/text. Update after the code change lands, not before.
#
# Exit status: 0 with hits, 1 with no hits, 2 on usage error.

set -u

if [ $# -lt 1 ] || [ -z "$1" ]; then
  echo "usage: impact-scan.sh <identifier> [dir]" >&2
  exit 2
fi

IDENT="$1"
DIR="${2:-.}"

if [ ! -d "$DIR" ]; then
  echo "impact-scan.sh: not a directory: $DIR" >&2
  exit 2
fi

RAW="$(mktemp)"
CLASSIFIED="$(mktemp)"
trap 'rm -f "$RAW" "$CLASSIFIED"' EXIT

# Per-file hit counts; -F fixed string, -I skip binaries; drop zero-count lines.
grep -rIcF \
  --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=dist \
  --exclude-dir=build --exclude-dir=vendor --exclude-dir=__pycache__ \
  -- "$IDENT" "$DIR" 2>/dev/null | grep -v ':0$' > "$RAW" || true

classify() {
  # $1 = file path; echoes one bucket name.
  f="$1"
  lf=$(printf '%s\n' "$f" | tr '[:upper:]' '[:lower:]')
  base="${lf##*/}"

  case "$lf" in
    */vendor/*|*/vendors/*|*/third_party/*|*/thirdparty/*|*/.venv/*|*/venv/*|*/site-packages/*|*/node_modules/*)
      echo vendored; return ;;
  esac

  case "$lf" in
    */gen/*|*/generated/*|*/__snapshots__/*|*/coverage/*|*/.next/*|*.min.js|*.min.css|*.snap|*.pb.go|*_pb2.py)
      echo generated; return ;;
  esac
  case "$base" in
    package-lock.json|yarn.lock|pnpm-lock.yaml|cargo.lock|poetry.lock|gemfile.lock|composer.lock|uv.lock|go.sum)
      echo generated; return ;;
  esac
  if head -n 5 "$f" 2>/dev/null | grep -qiE 'auto-generated|do not edit|@generated|code generated by'; then
    echo generated; return
  fi

  case "$lf" in
    */test/*|*/tests/*|*/__tests__/*|*/spec/*|*/specs/*|*/testdata/*|*/fixtures/*)
      echo test; return ;;
  esac
  case "$base" in
    *.test.*|*.spec.*|*_test.*|*_spec.*|test_*|conftest.py)
      echo test; return ;;
  esac

  case "$lf" in
    */docs/*|*/doc/*) echo docs; return ;;
  esac
  case "$base" in
    *.md|*.markdown|*.rst|*.txt|*.adoc) echo docs; return ;;
  esac

  echo caller
}

while IFS= read -r line; do
  path="${line%:*}"
  count="${line##*:}"
  bucket="$(classify "$path")"
  printf '%s\t%s\t%s\n' "$bucket" "$count" "$path" >> "$CLASSIFIED"
done < "$RAW"

total=$(wc -l < "$CLASSIFIED" | tr -d ' ')
if [ "$total" -eq 0 ]; then
  echo "impact-scan: no hits for '$IDENT' under $DIR"
  exit 1
fi

echo "impact-scan: '$IDENT' under $DIR — $total file(s) with hits"
echo
echo "== counts =="
for b in caller test generated vendored docs; do
  n=$(awk -F '\t' -v b="$b" '$1 == b' "$CLASSIFIED" | wc -l | tr -d ' ')
  echo "  $b: $n"
done
echo
echo "== hits =="
for b in caller test generated vendored docs; do
  awk -F '\t' -v b="$b" '$1 == b { printf "  [%-9s] %s (%s hits)\n", $1, $3, $2 }' "$CLASSIFIED"
done
echo
echo "NOTE: the caller bucket is a to-read list, not a to-edit list — open each caller"
echo "far enough to know whether your change affects it before the first edit (rule 2d)."
